<?php
	define("FS_CLIENT_ID", "LMYVS1KHOJNIMDD4DQ3DVWQ2GQ0OT4KEDVXX3PZTMD5AA4WS");
	define("FS_CLIENT_SECRET", "GZBUKDHFLKJDHI14EDQ1V5VGF12CSI40FWZ13PGM3ESELBQ1");
	define("FS_REDIRECT_URI", "http://localhost/semester_project");
?>